name: AI Swarm Orchestration

on:
  push:
    branches:
      - main
    paths:
      - 'tasks/**'  # Триггер на новые задачи от Codex
  workflow_dispatch:
    inputs:
      task_description:
        description: 'Задача для роя'
        required: true
        default: 'Refactor login module'

jobs:
  swarm-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          pip install -r codex-swarm-engine/requirements.txt
          
      - name: Run LangGraph Swarm
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Запуск графа, который прочитает задачу и выполнит работу
          python3 codex-swarm-engine/src/graph.py
          
      - name: Commit Agent Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 AI Swarm: Task Completed"
          branch: main
